"""esquema inicial subvfy

Revision ID: 827c98b6a656
Revises: 
Create Date: 2026-09-17 03:50:01.160441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '827c98b6a656'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convocatoria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo_bdns', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('nivel_administracion', sa.String(length=20), nullable=True),
    sa.Column('administracion', sa.String(length=200), nullable=True),
    sa.Column('organo_convocante', sa.String(length=300), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('url_portal_oficial', sa.String(length=500), nullable=True),
    sa.Column('financiada_mrr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sincronizado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("nivel_administracion IN ('estado', 'ccaa', 'local', 'otros')", name='ck_convocatoria_nivel'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_bdns')
    )
    op.create_table('empresa',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nif', sa.String(length=15), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('tamano', sa.String(length=20), nullable=True),
    sa.Column('ccaa', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='activa', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("estado IN ('activa', 'inactiva')", name='ck_empresa_estado'),
    sa.CheckConstraint("tamano IN ('micro', 'pequena', 'mediana', 'grande')", name='ck_empresa_tamano'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('rol',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("codigo IN ('admin', 'gestor', 'usuario')", name='ck_rol_codigo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('analisis_ia',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('convocatoria_id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=True),
    sa.Column('tipo_analisis', sa.String(length=30), nullable=False),
    sa.Column('modelo_ia', sa.String(length=60), nullable=False),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_idoneidad', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='pendiente', nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_salida', sa.Integer(), nullable=True),
    sa.Column('coste_estimado', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('generado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'procesando', 'completado', 'error')", name='ck_analisis_estado'),
    sa.CheckConstraint("score_idoneidad IS NULL OR tipo_analisis = 'idoneidad'", name='ck_analisis_score_solo_idoneidad'),
    sa.CheckConstraint("tipo_analisis IN ('resumen', 'requisitos_clave', 'idoneidad', 'riesgos')", name='ck_analisis_tipo'),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatoria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analisis_ia_convocatoria', 'analisis_ia', ['convocatoria_id'], unique=False)
    op.create_index('ix_analisis_ia_empresa', 'analisis_ia', ['empresa_id'], unique=False, postgresql_where='empresa_id IS NOT NULL')
    op.create_index('ix_analisis_ia_resultado', 'analisis_ia', ['resultado'], unique=False, postgresql_using='gin')
    op.create_table('empresa_palabra_clave',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('palabra', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'palabra', name='uq_empresa_palabra')
    )
    op.create_table('usuario',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('empresa_id', sa.BigInteger(), nullable=False),
    sa.Column('rol_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='activo', nullable=False),
    sa.Column('ultimo_acceso_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("estado IN ('activo', 'inactivo', 'bloqueado')", name='ck_usuario_estado'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_usuario_email', 'usuario', ['email'], unique=False)
    op.create_index('ix_usuario_empresa', 'usuario', ['empresa_id'], unique=False)
    op.create_table('alerta',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('texto_busqueda', sa.String(length=300), nullable=True),
    sa.Column('nivel_administracion', sa.String(length=20), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=True),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('solo_mrr', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('frecuencia', sa.String(length=20), server_default='diaria', nullable=False),
    sa.Column('canal_notificacion', sa.String(length=20), server_default='email', nullable=False),
    sa.Column('activa', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('ultima_ejecucion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("canal_notificacion IN ('email', 'plataforma', 'ambos')", name='ck_alerta_canal'),
    sa.CheckConstraint("frecuencia IN ('inmediata', 'diaria', 'semanal')", name='ck_alerta_frecuencia'),
    sa.CheckConstraint("nivel_administracion IN ('estado', 'ccaa', 'local', 'otros')", name='ck_alerta_nivel'),
    sa.CheckConstraint('fecha_desde IS NULL OR fecha_hasta IS NULL OR fecha_desde <= fecha_hasta', name='ck_alerta_rango_fechas'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerta_activa', 'alerta', ['activa'], unique=False, postgresql_where='activa = true')
    op.create_index('ix_alerta_usuario', 'alerta', ['usuario_id'], unique=False)
    op.create_table('conversacion_asistente',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('titulo', sa.String(length=200), server_default='Nueva conversación', nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='activa', nullable=False),
    sa.Column('ultima_actividad_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("estado IN ('activa', 'archivada')", name='ck_conversacion_estado'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversacion_usuario', 'conversacion_asistente', ['usuario_id', 'ultima_actividad_at'], unique=False)
    op.create_table('favorito',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('convocatoria_id', sa.BigInteger(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatoria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'convocatoria_id', name='uq_favorito_usuario_convocatoria')
    )
    op.create_index('ix_favorito_usuario', 'favorito', ['usuario_id'], unique=False)
    op.create_table('alerta_ejecucion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alerta_id', sa.BigInteger(), nullable=False),
    sa.Column('fecha_ejecucion_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('convocatorias_encontradas', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estado_envio', sa.String(length=20), nullable=False),
    sa.Column('detalle_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("estado_envio IN ('enviado', 'sin_novedades', 'error')", name='ck_alerta_ejecucion_estado'),
    sa.ForeignKeyConstraint(['alerta_id'], ['alerta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerta_ejecucion_alerta', 'alerta_ejecucion', ['alerta_id', 'fecha_ejecucion_at'], unique=False)
    op.create_table('alerta_organo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alerta_id', sa.BigInteger(), nullable=False),
    sa.Column('organo_bdns_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['alerta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alerta_id', 'organo_bdns_id', name='uq_alerta_organo')
    )
    op.create_table('alerta_region',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alerta_id', sa.BigInteger(), nullable=False),
    sa.Column('region_bdns_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['alerta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alerta_id', 'region_bdns_id', name='uq_alerta_region')
    )
    op.create_table('mensaje_asistente',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversacion_id', sa.BigInteger(), nullable=False),
    sa.Column('convocatoria_id', sa.BigInteger(), nullable=True),
    sa.Column('rol_emisor', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("rol_emisor IN ('usuario', 'asistente')", name='ck_mensaje_rol_emisor'),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversacion_asistente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mensaje_conversacion', 'mensaje_asistente', ['conversacion_id', 'created_at'], unique=False)
    op.create_table('alerta_ejecucion_convocatoria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alerta_ejecucion_id', sa.BigInteger(), nullable=False),
    sa.Column('convocatoria_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alerta_ejecucion_id'], ['alerta_ejecucion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['convocatoria_id'], ['convocatoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alerta_ejecucion_id', 'convocatoria_id', name='uq_alerta_ejecucion_convocatoria')
    )

    # FKs de auditoría con ciclo (rol/empresa/usuario): se añaden aquí,
    # después de crear todas las tablas, porque use_alter=True en
    # ForeignKeyConstraint dentro de create_table() no emite el ALTER
    # TABLE correspondiente — hay que hacerlo explícito.
    op.create_foreign_key('fk_convocatoria_created_by', 'convocatoria', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_convocatoria_updated_by', 'convocatoria', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_empresa_created_by', 'empresa', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_empresa_updated_by', 'empresa', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_rol_created_by', 'rol', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_rol_updated_by', 'rol', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_analisis_ia_created_by', 'analisis_ia', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_analisis_ia_updated_by', 'analisis_ia', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_empresa_palabra_clave_created_by', 'empresa_palabra_clave', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_empresa_palabra_clave_updated_by', 'empresa_palabra_clave', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_usuario_created_by', 'usuario', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_usuario_updated_by', 'usuario', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_alerta_created_by', 'alerta', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_alerta_updated_by', 'alerta', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_conversacion_asistente_created_by', 'conversacion_asistente', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_conversacion_asistente_updated_by', 'conversacion_asistente', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_favorito_created_by', 'favorito', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_favorito_updated_by', 'favorito', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_alerta_ejecucion_created_by', 'alerta_ejecucion', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_alerta_ejecucion_updated_by', 'alerta_ejecucion', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_alerta_organo_created_by', 'alerta_organo', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_alerta_organo_updated_by', 'alerta_organo', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_alerta_region_created_by', 'alerta_region', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_alerta_region_updated_by', 'alerta_region', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_mensaje_asistente_created_by', 'mensaje_asistente', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_mensaje_asistente_updated_by', 'mensaje_asistente', 'usuario', ['updated_by'], ['id'])
    op.create_foreign_key('fk_alerta_ejecucion_convocatoria_created_by', 'alerta_ejecucion_convocatoria', 'usuario', ['created_by'], ['id'])
    op.create_foreign_key('fk_alerta_ejecucion_convocatoria_updated_by', 'alerta_ejecucion_convocatoria', 'usuario', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Se quitan primero los FKs de auditoría añadidos al final de upgrade(),
    # antes de borrar ninguna tabla (evita el ciclo al revés).
    op.drop_constraint('fk_convocatoria_created_by', 'convocatoria', type_='foreignkey')
    op.drop_constraint('fk_convocatoria_updated_by', 'convocatoria', type_='foreignkey')
    op.drop_constraint('fk_empresa_created_by', 'empresa', type_='foreignkey')
    op.drop_constraint('fk_empresa_updated_by', 'empresa', type_='foreignkey')
    op.drop_constraint('fk_rol_created_by', 'rol', type_='foreignkey')
    op.drop_constraint('fk_rol_updated_by', 'rol', type_='foreignkey')
    op.drop_constraint('fk_analisis_ia_created_by', 'analisis_ia', type_='foreignkey')
    op.drop_constraint('fk_analisis_ia_updated_by', 'analisis_ia', type_='foreignkey')
    op.drop_constraint('fk_empresa_palabra_clave_created_by', 'empresa_palabra_clave', type_='foreignkey')
    op.drop_constraint('fk_empresa_palabra_clave_updated_by', 'empresa_palabra_clave', type_='foreignkey')
    op.drop_constraint('fk_usuario_created_by', 'usuario', type_='foreignkey')
    op.drop_constraint('fk_usuario_updated_by', 'usuario', type_='foreignkey')
    op.drop_constraint('fk_alerta_created_by', 'alerta', type_='foreignkey')
    op.drop_constraint('fk_alerta_updated_by', 'alerta', type_='foreignkey')
    op.drop_constraint('fk_conversacion_asistente_created_by', 'conversacion_asistente', type_='foreignkey')
    op.drop_constraint('fk_conversacion_asistente_updated_by', 'conversacion_asistente', type_='foreignkey')
    op.drop_constraint('fk_favorito_created_by', 'favorito', type_='foreignkey')
    op.drop_constraint('fk_favorito_updated_by', 'favorito', type_='foreignkey')
    op.drop_constraint('fk_alerta_ejecucion_created_by', 'alerta_ejecucion', type_='foreignkey')
    op.drop_constraint('fk_alerta_ejecucion_updated_by', 'alerta_ejecucion', type_='foreignkey')
    op.drop_constraint('fk_alerta_organo_created_by', 'alerta_organo', type_='foreignkey')
    op.drop_constraint('fk_alerta_organo_updated_by', 'alerta_organo', type_='foreignkey')
    op.drop_constraint('fk_alerta_region_created_by', 'alerta_region', type_='foreignkey')
    op.drop_constraint('fk_alerta_region_updated_by', 'alerta_region', type_='foreignkey')
    op.drop_constraint('fk_mensaje_asistente_created_by', 'mensaje_asistente', type_='foreignkey')
    op.drop_constraint('fk_mensaje_asistente_updated_by', 'mensaje_asistente', type_='foreignkey')
    op.drop_constraint('fk_alerta_ejecucion_convocatoria_created_by', 'alerta_ejecucion_convocatoria', type_='foreignkey')
    op.drop_constraint('fk_alerta_ejecucion_convocatoria_updated_by', 'alerta_ejecucion_convocatoria', type_='foreignkey')
    op.drop_table('alerta_ejecucion_convocatoria')
    op.drop_index('ix_mensaje_conversacion', table_name='mensaje_asistente')
    op.drop_table('mensaje_asistente')
    op.drop_table('alerta_region')
    op.drop_table('alerta_organo')
    op.drop_index('ix_alerta_ejecucion_alerta', table_name='alerta_ejecucion')
    op.drop_table('alerta_ejecucion')
    op.drop_index('ix_favorito_usuario', table_name='favorito')
    op.drop_table('favorito')
    op.drop_index('ix_conversacion_usuario', table_name='conversacion_asistente')
    op.drop_table('conversacion_asistente')
    op.drop_index('ix_alerta_usuario', table_name='alerta')
    op.drop_index('ix_alerta_activa', table_name='alerta', postgresql_where='activa = true')
    op.drop_table('alerta')
    op.drop_index('ix_usuario_empresa', table_name='usuario')
    op.drop_index('ix_usuario_email', table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('empresa_palabra_clave')
    op.drop_index('ix_analisis_ia_resultado', table_name='analisis_ia', postgresql_using='gin')
    op.drop_index('ix_analisis_ia_empresa', table_name='analisis_ia', postgresql_where='empresa_id IS NOT NULL')
    op.drop_index('ix_analisis_ia_convocatoria', table_name='analisis_ia')
    op.drop_table('analisis_ia')
    op.drop_table('rol')
    op.drop_table('empresa')
    op.drop_table('convocatoria')
    # ### end Alembic commands ###
